snow_hex_list = [[8, 2], [11, 1], [8, 0], [9, -1], [10, -2], [9, -3]]
water_hex_list = [[0, 4], [6, 0], [8, -2], [-1, -3], [0, -4], [5, -1]]
grass_hex_list = [
    [-4, 4],
    [-5, 3],
    [-4, 2],
    [-3, 1],
    [-2, 0],
    [1, 3],
    [3, 3],
    [5, 3],
    [7, 3],
    [0, 2],
    [4, 2],
    [-1, 1],
    [1, 1],
    [3, 1],
    [5, 1],
    [7, 1],
    [-3, -1],
    [-1, -1],
    [1, -1],
    [3, -1],
    [7, -1],
    [2, 0],
    [0, -2],
    [3, -3],
    [-3, -5],
    [-1, -5],
    [1, -5],
    [3, -5],
    [5, -5],
    [7, -5],
    [-2, -6],
    [2, -6],
    [6, -6],
]
mountain_hex_list = [
    [-2, 4],
    [4, 4],
    [8, 4],
    [9, 3],
    [10, 2],
    [9, 1],
    [4, -2],
    [12, 0],
    [11, -1],
    [7, -3],
    [5, -3],
    [6, -4],
    [-5, 1],
    [-7, 1],
]
dense_forest_hex_list = [
    [6, 4],
    [2, 4],
    [-3, 3],
    [-6, 2],
    [-6, 0],
    [-5, -1],
    [-7, -1],
    [-4, -2],
    [-3, -3],
    [-1, -3],
    [4, -4],
    [2, -4],
    [-2, -4],
    [-4, -4],
]
