grass_hex_list = [
    [0, 0],
    [-1, 1],
    [0, 2],
    [1, 3],
    [2, 4],
    [3, 5],
    [4, 6],
    [3, 3],
    [5, 3],
    [7, 3],
    [9, 3],
    [11, 3],
    [5, 1],
    [7, 1],
    [9, 1],
    [11, 1],
    [4, 2],
    [8, 2],
    [6, 4],
    [1, 5],
    [5, 5],
    [7, 5],
    [11, 5],
    [7, 7],
    [1, 9],
    [3, 9],
    [5, 9],
    [7, 9],
    [9, 9],
    [11, 9],
    [2, 10],
    [6, 10],
    [10, 10]
]
mountain_hex_list = [
    [2, 0],
    [8, 0],
    [12, 0],
    [13, 1],
    [14, 2],
    [16, 4],
    [15, 5],
    [13, 3],
    [-1, 3],
    [-3, 3],
    [8, 6],
    [9, 7],
    [10, 8],
    [11, 7]
]
dense_forest_hex_list = [
    [1, 1],
    [-2, 2],
    [-2, 4],
    [-1, 5],
    [0, 6],
    [1, 7],
    [2, 8],
    [3, 7],
    [0, 8],
    [-3, 5],
    [6, 8],
    [8, 8],
    [6, 0],
    [10, 0]
]
snow_hex_list = [[12, 2], [15, 3], [12, 4], [13, 5], [14, 6], [13, 7]]
water_hex_list = [[3, 1], [4, 0], [5, 7], [4, 8], [10, 4], [9, 5], [12, 6]]
